sudo: required
services:
  - docker

before_install:
  - docker build -t devazn/docker-react -f Dockerfile.dev .
  # we get the docker id back here

# travis assumes that the container will auto shutdown
# will wait
# npm by default in npm run test does not exit
script: 
  - docker run -e CI=true devazn/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-1"
  app: "docker-react"
  environment: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-542494515155"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  